# Help:  https://aka.ms/yaml

resources:
- repo: self

trigger:
- master

variables:
  chart-root: deployment/helm-chart
  chart-name: ParserAsServiceApi
  chart-path: $(chart-root)/$(chart-name)
  image-name:  vplauzon/pas-api

stages:
  - stage: build
    displayName: build
    dependsOn:  []
    jobs:
      - template: helm-build.yaml
        parameters:
          deployment-name:  build_helm_api
          deployment-display-name:  Build API Helm
          app-version-cs-path:  PasWebApi/ApiVersion.cs

  - stage: dev
    displayName: dev
    dependsOn:  build
    jobs:
      - template: helm-deploy.yaml
        parameters:
          environment:  dev
