# Help:  https://aka.ms/yaml

resources:
- repo: self

trigger:
- master

variables:
  chart-root: deployment/helm-chart
  chart-name: ParserAsServiceApi
  chart-path: $(chart-root)/$(chart-name)
  image-name:  vplauzon/pas-api

stages:
  - stage: build
    displayName: build
    dependsOn:  []
    jobs:
      # Docker Hub Repo:  https://hub.docker.com/repository/docker/vplauzon/pas-api
      - template: helm-build.yaml
        parameters:
          appVersionCsPath:  PasWebApi/ApiVersion.cs

  - stage: dev
    displayName: dev
    dependsOn:  build
    jobs:
      - template: helm-deploy.yaml
        parameters:
          environment:  dev
