# Help:  https://aka.ms/yaml

resources:
- repo: self

trigger:
- master

stages:
  - stage: build
    displayName: build
    dependsOn:  []
    jobs:
      # Docker Hub Repo:  https://hub.docker.com/repository/docker/vplauzon/pas-api
      - template: helm-build.yaml
        parameters:
          appVersionTxtPath:  deployment/AppVersion.txt
          appVersionCsPath:  PasWebApi/AppVersion.cs
          chartName: ParserAsServiceApi
          imageName: vplauzon/pas-api

  - stage: dev
    displayName: dev
    dependsOn:  build
    jobs:
      - template: helm-deploy.yaml
        parameters:
          environment:  dev
          chartName: ParserAsServiceApi
