parameters:
  appVersionTxtPath:  deployment/ApiVersion.txt
  appVersionCsPath:  ''
  chartName:  ''
  imageName:  ''
jobs:
  - deployment:  build_helm
    displayName: Build Helm
    environment:  build
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      chart-root: deployment/helm-chart
      chart-path: '$(chart-root)/${{ parameters.chartName }}'
    strategy:
      runOnce:
        deploy:
          steps:
          # Checkout:  https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git#checkout
          - checkout: self
          # Python script:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/python-script
          - task: PythonScript@0
            displayName: 'Manage Version'
            inputs:
              scriptPath: 'deployment/manage-version.py'
              arguments: '${{ parameters.appVersionTxtPath }} ${{ parameters.appVersionCsPath }} $(Build.BuildId) deployment/FullVersion.txt'
          # .NET Core tests:  https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core#run-your-tests
          - task: DotNetCoreCLI@2
            displayName: 'Run Unit Tests'
            inputs:
              command: test
              projects: '**/*UnitTest/*.csproj'
              arguments: -c release --configuration $(BuildConfiguration)
          # .NET Core publish:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli#publish
          - task: DotNetCoreCLI@2
            displayName: 'Build / Publish'
            inputs:
              command: publish
              publishWebProjects: True
              arguments: --configuration $(BuildConfiguration) --output build-output
              zipAfterPublish: True
          # Build Docker:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker#build-and-push
          - task: Docker@2
            displayName: Build and push Docker Image
            inputs:
              repository: ${{ parameters.imageName }}
              command:  buildAndPush
              Dockerfile: '**/Dockerfile'
              tags: '$(full-version)'
          # Helm tool installer:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/helm-installer
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'
          # Helm deploy:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy
          - task: HelmDeploy@0
            displayName:  Helm Package
            inputs:
              command: package
              chartPath: $(chart-path)
              chartVersion: '$(full-version)'
              destination:  $(Build.ArtifactStagingDirectory)/deployment/
          # Copy files:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files
          - task: CopyFiles@2
            displayName:  Copy deployment directory
            inputs:
              sourceFolder: deployment
              targetFolder: $(Build.ArtifactStagingDirectory)/deployment/
          # Publish artefacts:  https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)/deployment
              artifactName: deployment
