apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser-api-deploy
  labels:
    app: parser-api
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: parser-api
  template:
      metadata:
        labels:
          app: parser-api
      spec:
        containers:
        - name: myapi
          image: vplauzon/pas-api:{{.Chart.Version}}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 2
          ports:
          - containerPort: 80