name:  Continuous Build / Test

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    # See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore
    - name: Install dependencies
      run: dotnet restore code/GramParser-Full.sln
    - name: Build
      run: dotnet build code/GramParser-Full.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test code/GramParser-Full.sln --no-restore --verbosity normal
    
