name:  Azure Deploy

on:
  push:
    branches:
      - master
    paths:
      - deployment/gram-parser-infra.json
      - .github/workflows/infra-deploy.yaml

env:
  rg:  gram-parser

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      run: az login --service-principal -u ${{ secrets.sp_id }} -p ${{ secrets.sp_secret }} --tenant ${{ secrets.tenant_id }}
    - name: Deploy
      run: |
        cd deployment
        bash deploy-gram-parser-infra.sh $rg