name:  Azure Deploy

on:
  push:
    branches:
      - master
    paths:
      - deployment/gram-parser-infra.json
      - .github/workflows/infra-deploy.yaml

env:
  rg:  gram-parser

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Login
    # Using the user MI as exposed in https://yourazurecoach.com/2022/12/29/use-github-actions-with-user-assigned-managed-identity/
    - name: Log into Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
    # Deploy
    - name: Deploy
      run: |
        cd deployment
        bash deploy-gram-parser-infra.sh $rg