name:  Package Nuget Alpha

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore PasLib
    - name: Patch version
      run: python3 deployment/patch-nuget-version.py PasLib/PasLib.csproj ${{ github.run_id }}
    - name: Build
      run: dotnet build PasLib --configuration Release --no-restore